apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-price
  template:
    metadata:
      labels:
        app: flight-price
    spec:
      containers:
      - name: flight-price
        image: flight-price-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flight-price-service
spec:
  selector:
    app: flight-price
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer